[package]
name = "launcher"
version = "1.8.8"
edition = "2024"
authors = ["https://icedtea.classpath.org/wiki/IcedTea-Web"]

[dependencies]
[target.'cfg(windows)'.dependencies]
dunce = "1.0.5"
winapi = { version = "0.3.9", features = ["winreg"] }

[profile.release]
debug = false
opt-level = 3
lto = true
panic = "abort"
strip = true 
